name: build
# This workflow is  triggered on pushes, pull requests to the repository.
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-20.04
    container: ubuntu:16.04
    steps:
      - name: build seafile
        run: |
          #install deps 
          apt update -y
          apt install sudo -y
          sudo apt-get install autoconf automake libtool libevent-dev libcurl4-openssl-dev libgtk2.0-dev uuid-dev intltool libsqlite3-dev valac libjansson-dev cmake qtchooser qtbase5-dev libqt5webkit5-dev qttools5-dev qttools5-dev-tools libssl-dev wget zip unzip  -y
          #install downloads repo
          wget --content-disposition -nc https://github.com/haiwen/libsearpc/archive/v3.2.0.tar.gz  
          wget --content-disposition -nc https://github.com/haiwen/seafile/archive/v8.0.3.tar.gz
          wget --content-disposition -nc https://github.com/haiwen/seafile-client/archive/v8.0.3.tar.gz
          #unarchive
          mkdir ./archive
          cp libsearpc-3.2.0.tar.gz ./archive
          cp seafile-8.0.3.tar.gz ./archive
          cp seafile-client-8.0.3.tar.gz ./archive
          tar xf libsearpc-3.2.0.tar.gz
          tar xf seafile-8.0.3.tar.gz
          tar xf seafile-client-8.0.3.tar.gz
          rm -rf libsearpc-3.2.0.tar.gz 
          rm -rf seafile-8.0.3.tar.gz
          rm -rf seafile-client-8.0.3.tar.gz

          #build seafile
          export PREFIX=/usr
          export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
          export PATH="$PREFIX/bin:$PATH"
          cd libsearpc-3.2.0
          ./autogen.sh
          ./configure --prefix=$PREFIX
          make
          sudo make install
          cd ..
          cd seafile-8.0.3/
          ./autogen.sh
          ./configure --prefix=$PREFIX --disable-fuse
          make
          sudo make install
          cd ..
          cd seafile-client-8.0.3/
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX .
          make
          sudo make install
          cd ..
          # recover all we need 
          mkdir -p ~/seafile-tipi/lib-seafile 
          mkdir -p ~/seafile-tipi/seafile-exe 
          cp /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libcurl.so.4 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libevent_pthreads-2.0.so.5 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libevent_core-2.0.so.5 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libjansson.so.4 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libidn.so.11 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libsasl2.so.2 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/libsearpc.so.1 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 ~/seafile-tipi/lib-seafile/
          cp /lib/x86_64-linux-gnu/libssl.so.1.0.0 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libtasn1.so.6 ~/seafile-tipi/lib-seafile/
          cp /lib/x86_64-linux-gnu/libuuid.so.1 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libwind.so.0 ~/seafile-tipi/lib-seafile/
          cp /lib/x86_64-linux-gnu/libz.so.1 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/librtmp.so.1 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libhogweed.so.4 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libnettle.so.6 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libgssapi.so.3 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libkrb5.so.26 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libasn1.so.8 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libroken.so.18 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libheimbase.so.1 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libhx509.so.5 ~/seafile-tipi/lib-seafile/
          cp /lib/x86_64-linux-gnu/libcrypt.so.1 ~/seafile-tipi/lib-seafile/
          cp /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0  ~/seafile-tipi/lib-seafile/
          cp /lib/x86_64-linux-gnu/libglib-2.0.so.0 ~/seafile-tipi/lib-seafile/
          cp /usr/bin/seaf-daemon ~/seafile-tipi/seafile-exe/
          cp /usr/bin/seaf-cli ~/seafile-tipi/seafile-exe/
          cd ~/
          zip -r seafile-tipi.zip  ~/seafile-tipi
      - uses: actions/upload-artifact@v3
        with:
          name: seafile_artifact
          path: ~/seafile-tipi.zip





